// Name: Rahim
// Surname: Rzayev
/* Description: An application has been provided for the purpose of determining whether individuals are suitable for riding a roller coaster.
The application is designed to gather information about the individual's age, height, weight, and any existing back or heart troubles.
To proceed with the evaluation, the user is required to enter these details into the application.
Once all the necessary information has been entered, the application features "check" buttons that need to be pressed.
Upon pressing these buttons, a message will be displayed in the TextField, providing the user with the outcome of the evaluation.
*/

/**
 *
 * @author 
 * 
 */
public class RollerCoasterRide extends javax.swing.JFrame {

    /**
     * Creates new form RollerCoasterRide
     */
    public RollerCoasterRide() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        label = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        textfieldmain = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        heightincm = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        age1 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        weightinkg = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Roller Coaster");
        setForeground(new java.awt.Color(204, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 204));
        jLabel1.setText("Welcome to Roller Coaster");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 0, -1, -1));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 74, -1, -1));

        label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        label.setForeground(new java.awt.Color(0, 0, 204));
        label.setText("Height in cm?");
        getContentPane().add(label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 252, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("Do you have back trouble?");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 258, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 204));
        jLabel5.setText("Do you have heart trouble?");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 258, -1));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 43, 190, -1));

        textfieldmain.setBackground(new java.awt.Color(0, 204, 204));
        textfieldmain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldmainActionPerformed(evt);
            }
        });
        getContentPane().add(textfieldmain, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 324, 674, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(204, 0, 0));
        jButton2.setText("NO");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(633, 220, 80, -1));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(204, 0, 0));
        jButton4.setText("NO");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 280, 80, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 204));
        jLabel7.setText("What is your weight?");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 258, -1));

        heightincm.setBackground(new java.awt.Color(255, 153, 255));
        heightincm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heightincmActionPerformed(evt);
            }
        });
        getContentPane().add(heightincm, new org.netbeans.lib.awtextra.AbsoluteConstraints(545, 114, 76, -1));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 50, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 204));
        jLabel9.setText("How old are you?");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 50, 256, 30));

        age1.setBackground(new java.awt.Color(255, 153, 255));
        age1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                age1ActionPerformed(evt);
            }
        });
        getContentPane().add(age1, new org.netbeans.lib.awtextra.AbsoluteConstraints(545, 55, 76, -1));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(102, 102, 0));
        jButton5.setText("CHECK");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(631, 54, -1, -1));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(102, 102, 0));
        jButton6.setText("CHECK");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(631, 113, -1, -1));

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(102, 102, 0));
        jButton7.setText("CHECK");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(631, 173, -1, -1));

        weightinkg.setBackground(new java.awt.Color(255, 153, 255));
        weightinkg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weightinkgActionPerformed(evt);
            }
        });
        getContentPane().add(weightinkg, new org.netbeans.lib.awtextra.AbsoluteConstraints(547, 174, 76, -1));

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton8.setForeground(new java.awt.Color(0, 204, 0));
        jButton8.setText("YES");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 280, 80, -1));

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton9.setForeground(new java.awt.Color(0, 204, 0));
        jButton9.setText("YES");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(545, 221, 80, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 102));
        jButton1.setText("RESTART");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 374, -1, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 102));
        jButton3.setText("EXIT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(496, 374, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images (1).jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 210, 200));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textfieldmainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldmainActionPerformed
        // After entering information messages will be visible in this TextField.
    }//GEN-LAST:event_textfieldmainActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    textfieldmain.setText(" Congratulations!" + " You can skip to the fifth check. ");
    /*  This is a "NO" button in order to say you do not have a back trouble.     
        After pressing this button the information will be visible which is in the brackets.*/
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    textfieldmain.setText(" Congratulations!" + " You can ride roller coaster!");
    /*  This is a "NO" button in order to say you do not have a heart trouble.     
        After pressing this button the information will be visible which is in the brackets.*/
    }//GEN-LAST:event_jButton4ActionPerformed

    private void heightincmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_heightincmActionPerformed
    // I added this TextField in order to enter height. (This height should be in cm.)
    }//GEN-LAST:event_heightincmActionPerformed

    private void age1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_age1ActionPerformed
    // I added this TextField in order to enter age. 
    }//GEN-LAST:event_age1ActionPerformed

    private void weightinkgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weightinkgActionPerformed
    // I added this TextField in order to enter weight. (This weight should be in kg)
    }//GEN-LAST:event_weightinkgActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
    textfieldmain.setText(" We are sorry. " + " You can not ride roller coaster ");
    /*  This is a "YES" button in order to say you have a heart trouble.     
        After pressing this button the information will be visible which is in the brackets.*/
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
    textfieldmain.setText(" We are sorry. " + " You can not ride roller coaster ");
    /*  This is a "YES" button in order to say you have a back trouble.     
        After pressing this button the information will be visible which is in the brackets.*/
    }//GEN-LAST:event_jButton9ActionPerformed
    
    // This is a "CHECK" button in order to check information after entering age in the TextField.
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        {
      
    int age = Integer.valueOf(age1.getText()); //valueOf(age1) is an inbuilt method which is used to return an Integer instance representing the specified int value age.
      
    if //the condition in an if statement is a Boolean expression which evaluates to either true or false
            (age >= 18 && age <= 60) /* This sentence shows the age range of 18 and 60 years. 
                                        I wrote these statment in order to show two different messages on the screen.*/
    
    //If the entered age range is between 18 and 60, the text field will display this message which is inside the brackets.
    textfieldmain.setText(" Congratulations! Your age is suitable for our Roller Coaster. " + " You can skip to the second check. "); 
    
    else //an else statement is an alternative statement that is executed if the result of a previous test condition evaluates to false. 
    
    //If the entered age range is not between 18 and 60, the text field will display this message which is inside the brackets.
    textfieldmain.setText(" We are sorry. Your age is not suitable for our Roller Coaster. " + " You can not ride roller coaster. ");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    // This is a "CHECK" button in order to check information after entering weight in the TextField.
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        {
      
    int weight = Integer.valueOf(weightinkg.getText()); //valueOf(weightinkg) is an inbuilt method which is used to return an Integer instance representing the specified int value weight
      
      
    if (weight <= 90 && weight >= 40) /* This sentence shows the weight range of 40 and 90 years. 
                                        I wrote these statment in order to show two different messages on the screen.*/
    
    //If the entered weight range is between 40 and 90, the text field will display this message which is inside the brackets.
    textfieldmain.setText(" Congratulations! Your weight is suitable for our Roller Coaster. " + " You can skip to the fourth check. ");
    
    else //an else statement is an alternative statement that is executed if the result of a previous test condition evaluates to false. 
    
    //If the entered weight range is not between 40 and 90, the text field will display this message which is inside the brackets.    
    textfieldmain.setText(" We are sorry. Your weight is not suitable for our Roller Coaster. " + " You can not ride roller coaster. ");
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    // This is a "CHECK" button in order to check information after entering height in the TextField.
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        {
      
      
    int height = Integer.valueOf(heightincm.getText());//valueOf(heightincm) is an inbuilt method which is used to return an Integer instance representing the specified int value height.
      
      
    if (height <= 188 && height >= 122) /* This sentence shows the height range of 122 and 188 years. 
                                        I wrote these statment in order to show two different messages on the screen.*/
    
    //If the entered height range is between 122 and 188, the text field will display this message which is inside the brackets.    
    textfieldmain.setText(" Congratulations! Your height is suitable for our Roller Coaster. " + " You can skip to the third check. ");
    
    else //an else statement is an alternative statement that is executed if the result of a previous test condition evaluates to false. 
    
    //If the entered height range is not between 122 and 188, the text field will display this message which is inside the brackets.     
    textfieldmain.setText(" We are sorry. Your height is not suitable for our Roller Coaster. " + " You can not ride roller coaster. ");
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    // This a "RESTART" button in order to remove all information from all TextFields. 
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    heightincm.setText(null); //This removes information from TextFields(heightincm).
    textfieldmain.setText(null); //This removes information from TextFields(textfieldmain).
    age1.setText(null); //This removes information from TextFields(age1).
    weightinkg.setText(null); //This removes information from TextFields(weightinkg).
        
    
    }//GEN-LAST:event_jButton1ActionPerformed
    // I added this button in order to close application.
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    System.exit(0); //This code close page.
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RollerCoasterRide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RollerCoasterRide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RollerCoasterRide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RollerCoasterRide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RollerCoasterRide().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField age1;
    private javax.swing.JTextField heightincm;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel label;
    private javax.swing.JTextField textfieldmain;
    private javax.swing.JTextField weightinkg;
    // End of variables declaration//GEN-END:variables
}
